CSC517-Rails-Train-Ticketing-Sysytem/config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  get 'bookings/create'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :trains do
    resources :reviews
    collection do
      get 'search'
    end
    member do
      post 'book'
      delete 'cancel_booking'
    end
  end
  resources :trains
  resources :reviews, only: [:index]
  resources :reviews do
    collection do
      get 'search'
    end
  end
  resources :bookings, only: [:index]
  resources :bookings do
    collection do
      get 'search'
    end
  end
  root 'home#index'
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  get 'highly_rated_trains', to: "trains#get_highly_rated_trains", as: 'highly_rated_trains'
  resources :bookings, only: [:show]
end

CSC517-Rails-Train-Ticketing-Sysytem/app/models/train.rb
class Train < ApplicationRecord
    has_many :bookings, dependent: :destroy
    has_many :reviews, dependent: :destroy

    validates :number, :departure_station, :termination_station, :departure_date, :departure_time,
    :arrival_date, :arrival_time, :ticket_price, :train_capacity, :seats_left,
    presence: true
    validates :train_capacity, numericality: { greater_than_or_equal_to: 0, message: "should be a valid value" }
    validates :seats_left, numericality: { greater_than_or_equal_to: 0, message: "should be a non-negative number" }
    validates :seats_left, numericality: { less_than_or_equal_to: ->(train) { train.train_capacity }, message: "Seats left should be less than capacity" }
    validates :ticket_price, numericality: { greater_than_or_equal_to: 0, message: "should be a non-negative number" }
    validate :validate_departure_and_arrival

    private

    def validate_departure_and_arrival
      return unless departure_date && departure_time && arrival_date && arrival_time
  
      if departure_date > arrival_date || (departure_date == arrival_date && departure_time >= arrival_time)
        errors.add(:departure_date, "and time should be less than arrival date and time")
      end
    end
end

CSC517-Rails-Train-Ticketing-Sysytem/app/controllers/trains_controller.rb
class TrainsController < ApplicationController
    before_action :admin_authorized, only: [:new, :create, :edit, :update, :destroy]

    def index
        @trains = Train.where('departure_date >= ?', Date.today)
                .where('seats_left > ?', 0)
                .order(departure_date: :asc, departure_time: :asc)
        @rating_filter = params[:rating]
        if @rating_filter.present?
            @trains = @trains.where("average_rating >= ?", @rating_filter)
        end

        @departure_station = params[:departure_station]
        @termination_station = params[:termination_station]
  
        if @departure_station.present?
            @trains = @trains.where("LOWER(departure_station) LIKE ?", "%#{@departure_station.downcase}%")
        end
      
        if @termination_station.present?
            @trains = @trains.where("LOWER(termination_station) LIKE ?", "%#{@termination_station.downcase}%")
        end
    end

    def new
        @train = Train.new
    end
    
    def create
        @train = Train.new(train_params)
    
        if @train.save
          flash[:success] = 'Trained Created Sucessfully!'
          redirect_to trains_path
        else
          render :new, status: :unprocessable_entity
        end
    end

    def edit
        @train = Train.find(params[:id])
    end

    def update
        @train = Train.find(params[:id])
        if @train.update(train_params)
          flash[:success] = 'Train was successfully updated.'
          redirect_to trains_path
        else
          render :edit
        end
    end

    def get_highly_rated_trains
        @trains = Train.where('average_rating > ?', 3)
        render action: "index"
    end

    def book
        @train = Train.find(params[:id])
        @booking = Booking.new(train: @train, user: current_user)
        @booking.price = @train.ticket_price
        if @booking.save
          @train.decrement!(:seats_left)
          flash[:success] = "Booking successful! Your booking code is: #{@booking.booking_code} and price is #{@booking.price}. Go to View bookings section at home page to view all your bookings !"
        else
            flash[:failure] = 'Unfortunately your booking was not successful!'
        end
        redirect_to trains_path
    end
    
    def cancel_booking
        @train = Train.find(params[:id])
        @booking = current_user.bookings.find_by(train: @train)
    
        if @booking.destroy
          @train.increment!(:seats_left)
          flash[:success] = 'Booking successfully cancelled!'
        else
          flash[:success] = 'Booking failed to cancel! Please contact customer care!'
        end
        redirect_to trains_path
    end

    def show
        @train = Train.find(params[:id])
        @has_reviews = @train.reviews.any?
        @review = @train.reviews.find_by(user_id: current_user.id)
    end

    def destroy
        @train = Train.find(params[:id])
        @train.destroy
        flash[:success] = 'Train SUccessfully Deleted'
        respond_to do |format|
          format.html { redirect_to trains_url}
          format.json { head :no_content }
        end
    end

    private

    def train_params
      params.require(:train).permit(
        :number,
        :departure_station,
        :termination_station,
        :departure_date,
        :departure_time,
        :arrival_date,
        :arrival_time,
        :ticket_price,
        :train_capacity,
        :seats_left,
        :average_rating
      )
    end

    private

    def admin_authorized
      redirect_to root_path unless logged_in? && current_user.admin?
    end

end

CSC517-Rails-Train-Ticketing-Sysytem/app/helpers/trains_helper.rb
module TrainsHelper
end

CSC517-Rails-Train-Ticketing-Sysytem/app/views/trains/_form.html.erb
<div style="display: flex; justify-content: center; align-items: center; height: 60vh;">
  <div style="background-color: #f0f0f0; padding: 10px; border: 1px solid #ccc; border-radius: 5px; width: 300px;">
    <%= form_with(model: @train, local: true) do |form| %>

      <div class="field" style="margin-bottom: 10px;">
        <%= form.label :number %>
        <%= form.text_field :number, class: "form-control", style: "width: 100%;" %>
      </div>

      <div class="field" style="margin-bottom: 10px;">
        <%= form.label :departure_station %>
        <%= form.text_field :departure_station, class: "form-control", style: "width: 100%;" %>
      </div>

      <div class="field" style="margin-bottom: 10px;">
        <%= form.label :termination_station %>
        <%= form.text_field :termination_station, class: "form-control", style: "width: 100%;" %>
      </div>

      <div class="field" style="margin-bottom: 10px;">
        <%= form.label :departure_date %>
        <%= form.date_field :departure_date, class: "form-control", style: "width: 100%;" %>
      </div>

      <div class="field" style="margin-bottom: 10px;">
        <%= form.label :departure_time %>
        <%= form.time_field :departure_time, class: "form-control", style: "width: 100%;" %>
      </div>

      <div class="field" style="margin-bottom: 10px;">
        <%= form.label :arrival_date %>
        <%= form.date_field :arrival_date, class: "form-control", style: "width: 100%;" %>
      </div>

      <div class="field" style="margin-bottom: 10px;">
        <%= form.label :arrival_time %>
        <%= form.time_field :arrival_time, class: "form-control", style: "width: 100%;" %>
      </div>

      <div class="field" style="margin-bottom: 10px;">
        <%= form.label :ticket_price %>
        <%= form.text_field :ticket_price, class: "form-control", style: "width: 100%;" %>
      </div>

      <div class="field" style="margin-bottom: 10px;">
        <%= form.label :train_capacity %>
        <%= form.number_field :train_capacity, class: "form-control", style: "width: 100%;" %>
      </div>

      <div class="field" style="margin-bottom: 10px;">
        <%= form.label :seats_left %>
        <%= form.number_field :seats_left, class: "form-control", style: "width: 100%;" %>
      </div>

      <div class="actions">
        <%= form.submit "Create", class: "btn btn-primary", style: "width: 100%;" %>
      </div>
        <% if @train.errors.any? %>
            <div id="error_explanation" style="color: red;text-align:center;">
                <% @train.errors.full_messages.each do |message| %>
                    <div style="color: red;"><%= message %></div>
                <% end %>
            </div>
        <% end %>
    <% end %>
  </div>
</div>

CSC517-Rails-Train-Ticketing-Sysytem/app/views/trains/edit.html.erb
<h1 style="text-align:center"><%= action_name.capitalize %> Train</h1>

<%= render 'form' %>

<%= link_to 'Back', trains_path %>

CSC517-Rails-Train-Ticketing-Sysytem/app/views/trains/index.html.erb
  <% if flash[:success].present? %>
    <script>
      alert("<%= flash[:success] %>");
    </script>
  <% elsif flash[:error].present? %>
    <script>
      alert("<%= flash[:error] %>");
    </script>
  <% end %>
  <%= flash[:success]=nil %>
<h1 style="text-align:center">List of Trains</h1>

<div style="text-align: center; margin: 20px;">
  <%= form_tag trains_path, method: :get, class: "search-form" do %>
    <div style="margin-bottom: 10px;">
      <b>Search By Station:</b>
      <br>
      <%= text_field_tag :departure_station, params[:departure_station], placeholder: "Departure Station" %>
      <br>
      <%= text_field_tag :termination_station, params[:termination_station], placeholder: "Destination Station" %>
    </div>
    
    <div style="margin-bottom: 10px;">
      <label for="rating"><b>Filter by Minimum Rating:</b></label>
      <br>
      <%= select_tag :rating, options_for_select([["All", ""]] + (1..5).map { |i| [i.to_s, i.to_s] }, params[:rating]), id: "rating" %>
    </div>

    <div>
      <%= submit_tag "Submit Search/Selection", class: "btn-primary",  style: 'margin-left: 5px; color: black;font-weight: bold;' %>
    </div>
  <% end %>

  <button style="margin-top: 10px;"><%= link_to 'Clear Search/Selection', trains_path, class: 'clear-search btn-secondary', style: 'margin-left: 5px; color: black; font-weight: normal;' %></button>
</div>

<table class="table" style="border:1px solid black;text-align:center;margin: 0 auto;background-color:grey;padding:20px;">
  <thead>
    <tr>
      <th>Train Number</th>
      <th>Departure Station</th>
      <th>Termination Station</th>
      <th>Departure Date</th>
      <th>Departure Time</th>
      <th>Arrival Date</th>
      <th>Arrival Time</th>
      <th>Ticket Price</th>
      <th>Train Capacity</th>
      <th>Seats Left</th>
      <th>Rating</th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <% booking = train.bookings.find_by(user_id: current_user.id) %>
      <% review = train.reviews.find_by(user_id: current_user.id) %>
      <tr>
        <td><%= train.number %></td>
        <td><%= train.departure_station %></td>
        <td><%= train.termination_station %></td>
        <td><%= train.departure_date %></td>
        <td><%= train.departure_time&.strftime('%H:%M %p') %></td>
        <td><%= train.arrival_date %></td>
        <td><%= train.arrival_time&.strftime('%H:%M %p') %></td>
        <td><%= number_to_currency(train.ticket_price) %></td>
        <td><%= train.train_capacity %></td>
        <td><%= train.seats_left %></td>
        <td><%= train.average_rating %></td>
        <td><%= link_to 'View Details', train_path(train), class: 'btn btn-info' %></td>
        <td>
          <% if train.bookings.where(user_id: current_user.id).exists? %>
            <%= link_to 'Cancel Booking', cancel_booking_train_path(train), data: { turbo_method: :delete }, class: 'btn btn-danger' %>
          <% else %>
            <%= link_to 'Book', book_train_path(train), data: { turbo_method: :post } , class: 'btn btn-primary' %>
          <% end %>
        </td>
        <% if current_user && current_user.admin? %>
          <td>
            <%= link_to 'Edit', edit_train_path(train), class: 'btn btn-info' %>
          </td>
        <% end %>        
          <% if current_user && current_user.admin? %>
            <td>
                <%= link_to 'Delete', train, data: { turbo_method: :delete } , class: 'btn btn-danger' %>
          </td>
        <% end %>
        <% if booking && review %>
          <td>
            <%= link_to 'Edit Review', edit_train_review_path(id:review.id, train_id: train.id), class: 'btn btn-warning' %>
          </td>
        <% elsif booking %>
          <td>
            <%= link_to 'Create Review', new_train_review_path(train_id: train.id), class: 'btn btn-success' %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

CSC517-Rails-Train-Ticketing-Sysytem/app/views/trains/new.html.erb
<h1 style="text-align:center"><%= action_name.capitalize %> Train</h1>

<%= render 'form' %>

<%= link_to 'Back', trains_path %>

CSC517-Rails-Train-Ticketing-Sysytem/app/views/trains/show.html.erb
  <% if flash[:success].present? %>
    <script>
      alert("<%= flash[:success] %>");
    </script>
  <% elsif flash[:error].present? %>
    <script>
      alert("<%= flash[:error] %>");
    </script>
  <% end %>
  <%= flash[:success]=nil %>
<style>
  .reviews-container {
    max-height: 60vh;
    overflow-y: auto;
    background-color: #333;
    color: white;
    padding: 5px;
    margin-top:15px;
  }
</style>

<h1 style="text-align:center">Train Details - <%= @train.number %></h1>

<table class="table" style="border:1px solid black;text-align:center;margin: 0 auto;background-color:grey;padding:20px;">
  <thead>
    <tr>
      <th>Train Number</th>
      <th>Departure Station</th>
      <th>Termination Station</th>
      <th>Departure Date</th>
      <th>Departure Time</th>
      <th>Arrival Date</th>
      <th>Arrival Time</th>
      <th>Ticket Price</th>
      <th>Train Capacity</th>
      <th>Seats Left</th>
      <th>Rating</th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @train.number %></td>
        <td><%= @train.departure_station %></td>
        <td><%= @train.termination_station %></td>
        <td><%= @train.departure_date %></td>
        <td><%= @train.departure_time.strftime('%H:%M %p') %></td>
        <td><%= @train.arrival_date %></td>
        <td><%= @train.arrival_time.strftime('%H:%M %p') %></td>
        <td><%= number_to_currency(@train.ticket_price) %></td>
        <td><%= @train.train_capacity %></td>
        <td><%= @train.seats_left %></td>
        <td><%= @train.average_rating %></td>
      </tr>
  </tbody>
<table>

<div class="reviews-container">
  <h2 style="text-align:center;">Reviews</h2>
  <% if @has_reviews %>
    <%= render @train.reviews %>
  <% else %>
    <h3>No Reviews</h3>
  <% end %>
</div>