CSC517-Rails-Train-Ticketing-Sysytem/config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  get 'bookings/create'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :trains do
    resources :reviews
    collection do
      get 'search'
    end
    member do
      post 'book'
      delete 'cancel_booking'
    end
  end
  resources :trains
  resources :reviews, only: [:index]
  resources :reviews do
    collection do
      get 'search'
    end
  end
  resources :bookings, only: [:index]
  resources :bookings do
    collection do
      get 'search'
    end
  end
  root 'home#index'
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  get 'highly_rated_trains', to: "trains#get_highly_rated_trains", as: 'highly_rated_trains'
  resources :bookings, only: [:show]
end

CSC517-Rails-Train-Ticketing-Sysytem/app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :train

  before_create :generate_booking_code

  private

  def generate_booking_code
    self.booking_code = SecureRandom.random_number(1_000_000_000).to_s.rjust(9, '0')
  end
end

CSC517-Rails-Train-Ticketing-Sysytem/app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def show
  end

  def search
    load_bookings
    @bookings = @bookings.joins(:user, :train)
    @bookings = @bookings.where("lower(trains.number) LIKE ?", "%#{params[:train_q].downcase}%") if params[:train_q].present?
    render :index
  end

  def index
    load_bookings
  end

  private

  def load_bookings
    if current_user && current_user.admin?
      @bookings = Booking.all
    else
      @bookings = current_user.bookings
    end
  end
end

CSC517-Rails-Train-Ticketing-Sysytem/app/helpers/bookings_helper.rb
module BookingsHelper
end

CSC517-Rails-Train-Ticketing-Sysytem/app/views/bookings/index.html.erb
<% if current_user.admin? %>
<h1 style="text-align:center">All Bookings</h1>
<%else%>
<h1 style="text-align:center">Your Bookings</h1>
<% end %>


<div style="text-align:center">
<%= form_tag search_bookings_path, method: :get, id: 'search-form' do %>

    <%= label_tag 'Train' %>
    <%= text_field_tag :train_q, params[:train_q], placeholder: 'Search by train' %>
<%= submit_tag 'Search' %>
    <button><%= link_to 'Clear Search', bookings_path, class: 'clear-search', style: 'margin-left: 5px; color: black;' %></button>
<% end %>
</div>

<table style="border:1px solid black;text-align:center;margin: 0 auto;background-color:grey;padding:20px;">
<thead>
<tr>
  <% if current_user.admin? %>
    <th>User</th>
  <%end%>
  <th>Booking Code</th>
  <th>Train Number</th>
  <th>Source Station</th>
  <th>Destination Station</th>
  <th>Ticket Price</th>
  <th>Booking Date</th>
</tr>
</thead>
<tbody>
<% @bookings.each do |booking| %>
  <tr>
    <% if current_user.admin? %>
      <td><%= booking.user.name %></td>
    <%end%>
    <td><%= booking.booking_code %></td>
    <td><%= booking.train.number %></td>
    <td><%= booking.train.departure_station %></td>
    <td><%= booking.train.termination_station %></td>
    <td><%= number_to_currency(booking.train.ticket_price) %></td>
    <td><%= booking.created_at %></td>
  </tr>
<% end %>
</tbody>
</table>