CSC517-Rails-Train-Ticketing-Sysytem/config/routes.rb
Rails.application.routes.draw do
  get 'bookings/new'
  get 'bookings/create'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users
  resources :trains do
    resources :reviews
    collection do
      get 'search'
    end
    member do
      post 'book'
      delete 'cancel_booking'
    end
  end
  resources :trains
  resources :reviews, only: [:index]
  resources :reviews do
    collection do
      get 'search'
    end
  end
  resources :bookings, only: [:index]
  resources :bookings do
    collection do
      get 'search'
    end
  end
  root 'home#index'
  get 'signup', to: "users#new", as: 'signup'
  get 'login', to: "sessions#new", as: 'login'
  get 'logout', to: "sessions#destroy", as: 'logout'
  get 'highly_rated_trains', to: "trains#get_highly_rated_trains", as: 'highly_rated_trains'
  resources :bookings, only: [:show]
end

CSC517-Rails-Train-Ticketing-Sysytem/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :set_train, only: [:create, :edit, :update]
    before_action :set_review, only: [:edit, :update]

    def index
      @reviews = Review.all
    end

    def new
      @train = Train.find(params[:train_id])
      @review = Review.new
    end

    def search
      @reviews = Review.all
      filter_reviews(params[:user_q], params[:train_q])
      render :index
    end
  
    def create
      @review = current_user.reviews.new(review_params)
      @review.train = @train
  
      if @review.save
        update_train_rating
        flash[:success] = "Review was successfully created."
        redirect_to @train
      else
        render 'trains/show'
      end
    end
  
    def edit
      @train = Train.find(params[:train_id])
      @review = Review.find(params[:id])
      unless @review.user == current_user
        redirect_to @train, alert: 'You cannot edit reviews written by other users.'
      end
    end
  
    def update
      if @review.user == current_user
        if @review.update(review_params)
          update_train_rating
          redirect_to @train, notice: 'Review was successfully updated.'
        else
          render :edit
        end
      else
        redirect_to @train, alert: 'You cannot edit reviews written by other users.'
      end
    end
  
    private
  
    def set_train
      @train = Train.find(params[:train_id])
    end
  
    def set_review
      @review = @train.reviews.find(params[:id])
    end
  
    def review_params
      params.require(:review).permit(:feedback, :rating)
    end

    def update_train_rating
      average_rating = @train.reviews.average(:rating)
      @train.update(average_rating: average_rating)
    end

    def filter_reviews(user_query, train_query)
      @reviews = @reviews.joins(:user, :train)
      @reviews = @reviews.where("lower(users.name) LIKE ?", "%#{user_query.downcase}%") if user_query.present?
      @reviews = @reviews.where("lower(trains.number) LIKE ?", "%#{train_query.downcase}%") if train_query.present?
    end
  end
  

CSC517-Rails-Train-Ticketing-Sysytem/app/helpers/reviews_helper.rb
module ReviewsHelper
end

CSC517-Rails-Train-Ticketing-Sysytem/app/views/reviews/_form.html.erb
<div style="display: flex; justify-content: center; align-items: center; height: 20vh;">
  <div style="background-color: #f0f0f0; padding: 20px; border: 1px solid #ccc; border-radius: 5px; width: 300px;">
    <%= form_for([@train, @review], html: { style: 'display: inline-block;' }) do |f| %>
        <%= f.label :rating %>
        <%= f.number_field :rating, in: 1..5 %>
        <%= f.label :feedback %>
        <%= f.text_area :feedback %>

      <% if @review.persisted? %>
        <%= f.submit 'Update Review', data: { turbo_method: :put }  %>
      <% else %>
        <%= f.submit 'Create Review', method: :post %>
      <% end %>
    <% end %>
  </div>
</div>

CSC517-Rails-Train-Ticketing-Sysytem/app/views/reviews/_review.html.erb
<style>

  .review {
    background-color: #f1f1f1;
    padding: 15px;
    margin-bottom: 15px;
    border-radius: 8px;
    color:black;
  }

  .review h3 {
    margin-bottom: 5px;
  }

  .review p {
    margin: 0;
  }

  .edit-link {
    display: inline-block;
    margin-top: 10px;
  }
</style>

<div class="review">
    <b>User ID: <%= review.user.name %></b>
    <p>Rating: <%= review.rating %></p>
    <p>Feedback: <%= review.feedback.present? ? review.feedback : 'Not Provided' %></p>
</div>

CSC517-Rails-Train-Ticketing-Sysytem/app/views/reviews/edit.html.erb
<header>
        <nav>
            <div class="navbar">
                <div class="logo">
                  <%= image_tag("rail.png", alt: "Train Icon") %>
                  <span>Train Ticketing System</span>
                </div>
                <ul>
                    <li><%= link_to 'Home', root_path %></li>
                    <li><%= link_to 'Edit Account', edit_user_path(current_user) %></li>
                    <% unless current_user && current_user.admin? %>
                        <li><%= link_to 'Destroy', current_user, data: { turbo_method: :delete } , class: 'btn btn-danger' %></li>
                    <% end %>
                    <li><%= link_to 'Logout', logout_path(current_user) %></li>
                </ul>
            </div>
        </nav>
</header>

<h1 style="text-align:center"><%= action_name.capitalize %> Review</h1>

<%= render 'form' %>

CSC517-Rails-Train-Ticketing-Sysytem/app/views/reviews/index.html.erb
<h1 style="text-align:center">All Reviews</h1>

<div style="text-align:center">
    <%= form_tag search_reviews_path, method: :get do %>
        <%= label_tag 'User' %>
        <%= text_field_tag :user_q, params[:user_q], placeholder: 'Search by user' %>

        <%= label_tag 'Train' %>
        <%= text_field_tag :train_q, params[:train_q], placeholder: 'Search by train' %>

    <%= submit_tag 'Search' %>
        <button><%= link_to 'Clear Search', reviews_path, class: 'clear-search', style: 'margin-left: 5px; color: black;' %></button>
    <% end %>
</div>

<table class="table" style="border:1px solid black;text-align:center;margin: 0 auto;background-color:grey;padding:20px;">
  <thead>
    <tr>
      <th>User</th>
      <th>Train</th>
      <th>Rating</th>
      <th>Comment</th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.user.name %></td>
        <td><%= review.train.number %></td>
        <td><%= review.rating %></td>
        <td><%= review.feedback %></td>
      </tr>
    <% end %>
  </tbody>
</table>

CSC517-Rails-Train-Ticketing-Sysytem/app/views/reviews/new.html.erb
<h1 style="text-align:center"><%= action_name.capitalize %> Review</h1>

<%= render 'form' %>